-- Database: blockbuster

-- DROP DATABASE blockbuster;

CREATE TABLE TEMPORAL(
    NOMBRE_CLIENTE VARCHAR(40),
    CORREO_CLIENTE VARCHAR(65),
    CLIENTE_ACTIVO VARCHAR(3),
    FECHA_CREACION TIMESTAMP,
    TIENDA_PREFERIDA VARCHAR(10),
    DIRECCION_CLIENTE VARCHAR(100),
    CODIGO_POSTAL_CLIENTE VARCHAR(5),
    CIUDAD_CLIENTE VARCHAR(60),
    PAIS_CLIENTE VARCHAR(50),
    FECHA_RENTA TIMESTAMP,
    FECHA_RETORNO TIMESTAMP,
    MONTO_A_PAGAR FLOAT,
    FECHA_PAGO TIMESTAMP,
    NOMBRE_EMPLEADO VARCHAR(40),
    CORREO_EMPLEADO VARCHAR(65),
    EMPLEADO_ACTIVO VARCHAR(3),
    TIENDA_EMPLEADO VARCHAR(10),
    USUARIO_EMPLEADO VARCHAR(30),
    CONTRASENA_EMPLEADO VARCHAR(256),
    DIRECCION_EMPLEADO VARCHAR(100),
    CODIGO_POSTAL_EMPLEADO VARCHAR(5),
    CIUDAD_EMPLEADO VARCHAR(60),
    PAIS_EMPLEADO VARCHAR(50),
    NOMBRE_TIENDA VARCHAR(10),
    ENCARGADO_TIENDA VARCHAR(40),
    DIRECCION_TIENDA VARCHAR(100),
    CODIGO_POSTAL_TIENDA VARCHAR(5),
    CIUDAD_TIENDA VARCHAR(60),
    PAIS_TIENDA VARCHAR(50),
    TIENDA_PELICULA VARCHAR(10),
    NOMBRE_PELICULA VARCHAR(60),
    DESCRIPCION_PELICULA VARCHAR(200),
    ANO_LANZAMIENTO VARCHAR(4),
    DIAS_RENTA SMALLINT,
    COSTO_RENTA FLOAT,
    DURACION SMALLINT,
    COSTO_POR_DANO FLOAT,
    CLASIFICACION VARCHAR(4),
    LENGUAJE_PELICULA VARCHAR(60),
    CATEGORIA_PELICULA VARCHAR(30),
    ACTOR_PELICULA VARCHAR(100)
);

DROP TABLE TEMPORAL;