-- Tabla Pais 
INSERT 
    INTO PAIS (NOMBRE)
SELECT
    DISTINCT NOMBRE
FROM
    (
    SELECT
        DISTINCT PAIS_CLIENTE AS NOMBRE
    FROM
        TEMPORAL
    UNION 
    SELECT
        DISTINCT PAIS_EMPLEADO AS NOMBRE
    FROM
        TEMPORAL
    UNION
    SELECT
        DISTINCT PAIS_TIENDA AS NOMBRE
    FROM
        TEMPORAL
    ) SUB
WHERE 
    NOMBRE
IS NOT 
    NULL;

-- Tabla clasificacion 
INSERT 
    INTO CLASIFICACION (NOMBRE)
SELECT
    DISTINCT CLASIFICACION
FROM
    TEMPORAL
WHERE 
    CLASIFICACION
IS NOT 
    NULL;

-- tABLA CATEGORIA 
INSERT 
    INTO CATEGORIA (NOMBRE)
SELECT 
    DISTINCT CATEGORIA_PELICULA
FROM
    TEMPORAL
WHERE
    CATEGORIA_PELICULA
IS NOT
    NULL;

-- TABLA ACTOR 
INSERT 
    INTO ACTOR (NOMBRE, APELLIDO)
SELECT 
    DISTINCT
    (SELECT A[1] FROM REGEXP_SPLIT_TO_ARRAY(ACTOR_PELICULA, ' ') AS DT(A)) AS NOMBRE,
    (SELECT A[2] FROM REGEXP_SPLIT_TO_ARRAY(ACTOR_PELICULA, ' ') AS DT(A)) AS APELLIDO
FROM
    TEMPORAL
WHERE
    ACTOR_PELICULA
IS NOT
    NULL;

-- TABLA IDIOMA 
INSERT 
    INTO IDIOMA (NOMBRE)
SELECT 
    DISTINCT LENGUAJE_PELICULA
FROM
    TEMPORAL 
WHERE
    LENGUAJE_PELICULA
IS NOT
    NULL;

-- TABLA CIUDAD 
INSERT 
    INTO CIUDAD (NOMBRE, CODIGO_POSTAL, PAIS_ID_PAIS)
SELECT 
    NOMBREC, CODIGO_POSTAL, ID_PAIS
FROM
    (
    SELECT
        DISTINCT  CIUDAD_EMPLEADO AS NOMBREC, 
        CODIGO_POSTAL_EMPLEADO AS CODIGO_POSTAL, ID_PAIS
    FROM 
        TEMPORAL
    INNER JOIN 
        PAIS
    ON 
        PAIS_EMPLEADO = NOMBRE
    UNION
    SELECT
        DISTINCT  CIUDAD_TIENDA AS NOMBREC, 
        CODIGO_POSTAL_TIENDA AS CODIGO_POSTAL, ID_PAIS
    FROM 
        TEMPORAL
    INNER JOIN 
        PAIS
    ON 
        PAIS_TIENDA = NOMBRE
    UNION
    SELECT
        DISTINCT  CIUDAD_CLIENTE AS NOMBREC, 
        CODIGO_POSTAL_CLIENTE AS CODIGO_POSTAL, ID_PAIS
    FROM 
        TEMPORAL
    INNER JOIN 
        PAIS
    ON 
        PAIS_CLIENTE = NOMBRE
    ) SUB
WHERE
    NOMBREC
IS NOT
    NULL;


-- TABLA TIENDA 
INSERT 
    INTO TIENDA (DIRECCION, NOMBRE, CIUDAD_ID_CIUDAD)
SELECT 
    DISTINCT DIRECCION_TIENDA, NOMBRE_TIENDA, ID_CIUDAD 
FROM 
    TEMPORAL
INNER JOIN 
    CIUDAD
ON 
    CIUDAD_TIENDA = NOMBRE
WHERE
    NOMBRE_TIENDA
IS NOT
    NULL
ORDER BY
    NOMBRE_TIENDA
ASC;
