DROP TABLE PAIS CASCADE;

DROP TABLE CLASIFICACION CASCADE;

DROP TABLE CATEGORIA CASCADE;

DROP TABLE ACTOR CASCADE;

DROP TABLE IDIOMA CASCADE;

DROP TABLE CIUDAD CASCADE;

DROP TABLE TIENDA CASCADE;

DROP TABLE EMPLEADO CASCADE;

DROP TABLE CLIENTE CASCADE;

DROP TABLE PELICULA CASCADE;

DROP TABLE RENTA CASCADE;

DROP TABLE INVENTARIO CASCADE;

DROP TABLE CATEGORIA_PELICULA CASCADE;

DROP TABLE ACTOR_PELICULA CASCADE;

DROP TABLE lenguaje_pelicula CASCADE;